### ISSUE TITLE
CI failure

### ISSUE THREAD

**Issue by lancoer** [Axis-Fi/axis-utils#1]
Hi, why are you keep using broken CI/CD pipeline?
I think if you want to keep using `pnpm` for lint checker you should insert `pnpm` module using command lines for installation.

**Comment by lancoer** [comment]
@0xJem Try inserting like this from line 28 of [test.yaml](https://github.com/Axis-Fi/axis-periphery/blob/e20a42124dbdc6f2a74659828c1bc24dea4250ea/.github/workflows/test.yml):

```
- name: Install pnpm
        uses: pnpm/action-setup@v3
        with:
            version: 8
```
